//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteApplication.robotSimulator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="robotSimulator.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMotion", ReplyAction="http://tempuri.org/IService/getMotionResponse")]
        string getMotion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/setMotion", ReplyAction="http://tempuri.org/IService/setMotionResponse")]
        void setMotion(string newMotion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getSensorUpdate", ReplyAction="http://tempuri.org/IService/getSensorUpdateResponse")]
        double[] getSensorUpdate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/updateSensor", ReplyAction="http://tempuri.org/IService/updateSensorResponse")]
        void updateSensor(double front, double left, double right, double rear, double newCompass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/sendMessage", ReplyAction="http://tempuri.org/IService/sendMessageResponse")]
        void sendMessage(string newMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/receiveMessage", ReplyAction="http://tempuri.org/IService/receiveMessageResponse")]
        string receiveMessage();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : RemoteApplication.robotSimulator.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<RemoteApplication.robotSimulator.IService>, RemoteApplication.robotSimulator.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getMotion() {
            return base.Channel.getMotion();
        }
        
        public void setMotion(string newMotion) {
            base.Channel.setMotion(newMotion);
        }
        
        public double[] getSensorUpdate() {
            return base.Channel.getSensorUpdate();
        }
        
        public void updateSensor(double front, double left, double right, double rear, double newCompass) {
            base.Channel.updateSensor(front, left, right, rear, newCompass);
        }
        
        public void sendMessage(string newMsg) {
            base.Channel.sendMessage(newMsg);
        }
        
        public string receiveMessage() {
            return base.Channel.receiveMessage();
        }
    }
}
